### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by eduOS** [fourjay/upsql-vim#1]
I'm searching for such a plugin only to find yours. But seems empty.

**Comment by fourjay** [comment]
It ended up in an after/ftplugin file. Never got around to putting it here (sorry).
I've pulled the code from my ftplugin and put it here. It works, but it surely could be improved.

**Comment by fourjay** [comment]
I've added more "automagic" behavior. Now upcases after most all word boundaries.

**Comment by eduOS** [comment]
Great. Thanks for sharing. I'll try to contribute by all means.
